# Lobby Spawn
Lobby:
  world: 'world'
  x: 0
  y: 0
  z: 0

# Session Configuration
MinPlayers: 8
MaxPlayers: 24

# Server Configuration
MaxSlots: 250
MessagePrefix: '&7|&6Sky Wars&7| '
TabTitle: '&6Sky Wars'
TabFooter: '&6www.revtut.net'

# Utils Configuration
CoinsMultiplier: 1
