name: SkyWars
version: 1.0
description: RevTut Network SkyWars Plugin
author: RevTut
website: www.revtut.net
main: net.revtut.skywars.SkyWars

############
# COMANDOS #
############

commands:

# All commands
  information:
    description: Information about a game
    aliases: [info, status, informationen, informacao, informacion]
  statistics:
    description: Statistics of the player
    aliases: [stats, statistiques, statistik, estatisticas, estadisticas]

##############
# PERMISSOES #
##############

permissions:

# Chat
  rev.advertisment:
    description: Permission to advertise
    default: op
  rev.badlanguage:
    description: Permission to use bad language
    default: op
  rev.capslock:
    description: Permission to chat in capslock
    default: op
  rev.cooldownbp:
    description: Permission to bypass cooldown between messages and commands
    default: op
  rev.doublemsg:
    description: Permission to send double messages
    default: op
  rev.msgcolors:
    description: Permission to chat with colors
    default: op

# Game
  rev.nolosepoints:
    description: Permission to leave the game without losing points
    default: op