name: SkyWars
version: 1.0
description: RevTut Network SkyWars Plugin
author: RevTut
website: www.revtut.net
main: net.revtut.skywars.SkyWars

############
# COMANDOS #
############

commands:
# Appearance
  firework:
    description: Launch Firework
    aliases: [fw, feuartifice, feuerwerk, fogoartificio, fuegoartificiale]

# Building
  gamemode:
    description: Switch Game Mode
    aliases: [gm, modejeu, spielmodus, modojogo, modojuego]
  speed:
    description: Change Speed
    aliases: [vitesse, geschwindigkeit, velocidade, velocidad]

# Game
  information:
    description: Information about a game
    aliases: [info, status, informationen, informacao, informacion]
  statistics:
    description: Statistics of the player
    aliases: [stats, statistiques, statistik, estatisticas, estadisticas]

# Mechanics
  time:
    description: Change The Time and Weather
    aliases: [weather, temps, zeit, tempo, tiempo]

# Teleport
  spawn:
    description: Teleport To Spawn
  teleportall:
    description: Teleport All Players
    aliases: [tpall, teleportertous, alleteleportieren, teleportartodos, teletransportarsetodo]
  teleporthere:
    description: Teleport Player To You
    aliases: [tphere, teleporterici, teleportierenhier, teleportaraqui, teletransportarseaquí]
  teleportpos:
    description: Teleport To X Y Z
    aliases: [tppos, teleportierenpos, teleportarpos, telepuertopos]
  teleport:
    description: Teleport To Player [From Player]
    aliases: [tp, teleportieren, teleportar, telepuerto]

##############
# PERMISSOES #
##############

permissions:
# Appearance
  rev.firework:
    description: Permission to launch firework
    default: op

# Building
  rev.gamemode:
    description: Permission to switch game mode
    default: op
  rev.speed:
    description: Permission to change speed
    default: op

# Chat
  rev.advertisment:
    description: Permission to advertise
    default: op
  rev.badlanguage:
    description: Permission to use bad language
    default: op
  rev.capslock:
    description: Permission to chat in capslock
    default: op
  rev.cooldownbp:
    description: Permission to bypass cooldown between messages and commands
    default: op
  rev.doublemsg:
    description: Permission to send double messages
    default: op
  rev.msgcolors:
    description: Permission to chat with colors
    default: op

# Game
  rev.nolosepoints:
    description: Permission to leave the game without losing points
    default: op

# Mechanics
  rev.time:
    description: Permission to change the time
    default: op

# Teleport
  rev.teleportall:
    description: Permission to teleport all players
    default: op
  rev.teleporthere:
    description: Permission to teleport player to you
    default: op
  rev.teleportpos:
    description: Permission to teleport to x y z
    default: op
  rev.teleport:
    description: Permission to teleport to player [from player]
    default: op